const CONNECTOR_TYPE = {
  EV_CONNECTOR_TYPE_TYPE_2: "Tipo 2",
  EV_CONNECTOR_TYPE_CCS_COMBO_1: "CCS Combo 1",
  EV_CONNECTOR_TYPE_CCS_COMBO_2: "CCS Combo 2",
  EV_CONNECTOR_TYPE_CHADEMO: "CHAdeMO",
  EV_CONNECTOR_TYPE_J1772: "J1772",
};
export default CONNECTOR_TYPE;
